server:
  port: 8090
  servlet:
    context-path: /springboot-activemq
spring:
  jms:
    listener:
      auto-startup: true
      concurrency: 2
      max-concurrency: 4
    template:
      qos-enabled: true
      delivery-mode: PERSISTENT
      priority: 4
      time-to-live: 8640000
      receive-timeout: 1000
  activemq:
    broker-url: tcp://172.28.19.97:61616
    user: admin
    password: admin
    in-memory: false
    send-timeout: 3000
    pool:
      block-if-full: true
      block-if-full-timeout: -1
      create-connection-on-startup: true
      expiry-timeout: 0
      idle-timeout: 30000
      max-connections: 1
    packages:
      trust-all: true