spring: 
  application: 
    name: springcloud-client
eureka: 
  client: 
    serviceUrl: 
      # eureka注册中心的地址
      defaultZone: http://192.168.119.128:8001/eureka/,http://192.168.119.128:8002/eureka/,http://192.168.119.128:8003/eureka/