server:
  port: 8090
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 7e794b20-8e3e-4e74-ad32-a0c42e617d39
management:
  endpoints:
    web:
      exposure:
        include: '*'