server: 
  port: 9050
spring: 
  application: 
    name: gateway
  cloud: 
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 7c5c7d56-9c7d-4081-98cb-b4ab09818023
    gateway:
      discovery: 
        locator: 
          enabled: true
      routes:
        - id: http
          uri: http://172.28.19.70:80/
          predicates:
          - Path= /spc/book/getBookDetail/16801509277844
          filters: 
          - name: Test
            args: 
              op: root
              type: he
          
management:
  endpoints:
    web:
      exposure:
        include: "*" 
  endpoint:
      health:
        show-details: ALWAYS      