server: 
  port: 9000
  servlet:
    context-path: /springcloud-server  
spring: 
  application: 
    name: springcloud-server
eureka: 
  client: 
    serviceUrl: 
      # eureka注册中心的地址
      defaultZone: http://192.168.119.128:8001/eureka/,http://192.168.119.128:8002/eureka/,http://192.168.119.128:8003/eureka/