server: 
  port: 8090
  servlet: 
    context-path: /springboot-hystrix

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    testHystrixCommand5:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000