CREATE TABLE `USER`(
	ID BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '数据库自增列',
	PASSID VARCHAR(32) NOT NULL COMMENT '逻辑主键',
	PHONE VARCHAR(16) NOT NULL COMMENT '手机号',
	NICKNAME VARCHAR(64) DEFAULT NULL COMMENT '昵称',
	REGISTER_TIME DATETIME DEFAULT NULL COMMENT '注册时间',
	HEAD_IMG VARCHAR(256) DEFAULT NULL COMMENT '头像',
	PRIMARY KEY (ID),
	UNIQUE KEY ‘PASSID (PASSID)
) ENGINE = INNODB AUTO_INCREMENT=1; 